# This is a basic workflow to help you get started with Actions

name: nightly

# Controls when the workflow will run
on:
  # This can be used to automatically publish nightlies at UTC nighttime
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-nightly:
    runs-on: ubuntu-24.04

    outputs:
      is_active: ${{ steps.activity.outputs.is_active }}

    steps:
      - uses: actions/checkout@v4
      
      # copied from ruffle-rs/ruffle
      - name: Check for repo activity
        id: activity
        run: |
          # Skip activity check when manually triggered.
          if [ "${{ github.event_name }}" == "repository_dispatch" ] || [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            is_active=true
          elif [ "$(git rev-list --after="24 hours" ${{ github.sha }})" ]; then
            is_active=true
          else
            is_active=false
          fi
          echo "is_active=$is_active" >> $GITHUB_OUTPUT

  # This workflow contains a single job called "build"
  build-nightly:
    needs: create-nightly
    if: needs.create-nightly.outputs.is_active == 'true'

    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libgirepository-2.0-dev gir1.2-gtk-4.0

      - uses: mlugg/setup-zig@v1.2.1
        with:
          version: master
      
      - name: Generate bindings
        run: |
          zig build dist
      
      - uses: andelf/nightly-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'Nightly $$'
          prerelease: true
          body: |
            This is a nightly release. **Use it with caution**.
          files: |
            ./gtk4.tar.gz
